### ISSUE TITLE
Gazeboでロボットの関節を動かせない

### ISSUE THREAD

**Issue by tatsuma-ishiguro** [tatsuma-ishiguro/melew_ws#1]
Gazeboでロボットを動かそうとしており，指令値を送るプログラム（mockup_teleop.cpp）や簡単な脚の曲げ伸ばしプログラム(mockup_robot01.cpp)をC++で作成したが動かない．
【現状】
・rqt_guiを用いたところ，動かすことはできた．
・C++のプログラムを動かしている際にrostopic listやrostopic echoを確認するとtopicは存在した．
・rqt_grapfを確認すると，topicは存在するが/gazeboまでの矢印がない
・プログラムではなく，ターミナルから直接値をtopic通信したところ，上記と同じ結果に．

【問題】
PublishされているであろうtopicをGazeboがSubscribeしない原因が分からない．

**Comment by Hayabusa6863** [comment]
自分の環境でrostopic pub をしたところ，一応Hip, Knee, Wheel関節は動きました．
当初はxacroファイルなどの記述忘れが原因と思っていましたがそうでもないみたいです...


![rostopic_pub結果](https://user-images.githubusercontent.com/40104484/93890832-b7f31580-fd25-11ea-8e8e-c62b01619f6f.png)

また，
`rostopic pub /mockup_robot/wheel_position_controller/command std_msgs/Float64 "10.0"`
を実行した時のrqt-graphは以下のようになり，正常にtopicが届いていることが確認できました．
![ros_topic_pub_rqt_graph](https://user-images.githubusercontent.com/40104484/93892020-094fd480-fd27-11ea-8b8f-9103129dea45.png)

自分はGazeboに詳しいわけではないので，直接的な原因は不明ですがmockup_control.launchの記述，Publisherの記述部に何か問題がありそうな気がしています．

**Comment by Hayabusa6863** [comment]
動かない理由わかりました．
mockup_robot01.cppとmockup_teleop.cppでは
`"/mockup_pkg/UpperLeg_position_controller/command"`

と記載されていましたが，実際にrostopic listで確認した正しいtopic名は
`/mockup_robot/wheel_position_controller/command`
です．
（mockup_pkgではなく**mockup_robot**）

**Comment by tatsuma-ishiguro** [comment]
自分もやってみたら無事に動きました。
パッケージ名ではなくロボット名だったんですね…
ありがとうございました！！
